### ISSUE TITLE
Icons don't always get displayed when using hue: icon

### ISSUE THREAD

**Issue by tophers** [arallsopp/hass-hue-icons#196]
**Describe the bug**
Sometimes on the frontend of lovelace hue: icons are not displayed.  This is Chrome, Edge, Android App

**To Reproduce**
Add icon to front-end (at least with custom:button card, which could also be the issue, but only happens with hue: icons). Sometimes they are not displayed.

**Screenshots**
Showing missing icons
![kitchen_missing](https://user-images.githubusercontent.com/3819786/179865669-15a193fa-b537-4983-b6cb-4777062e578a.PNG)
and
![media_room_missing](https://user-images.githubusercontent.com/3819786/179865696-bd83fb58-349b-4e85-b12f-10d2e62461fb.PNG)

When I go into edit dashboard they come back, and typically stay for a while until a reload later. 
![kitchen_dining_edit](https://user-images.githubusercontent.com/3819786/179866049-852a9580-6e6e-4ce2-aec5-fa543b150e4f.PNG)
![media_room_edit](https://user-images.githubusercontent.com/3819786/179866053-9aba9921-3fca-44fc-8f1a-1e85704e1995.PNG)

**Desktop (please complete the following information):**
 - OS:  (Debian, HA Core)
 - Browser: Chrome: Android: Edge
 - Version: current version as of this report
 Browser console shows:  HASS-HUE-ICONS  Version 1.2.41 

**Smartphone (please complete the following information):**
 - Device: Android Pixel 3, 4 and 5

**Additional context**
Could be an interaction with custom button-card. 

YAML for the custom button card using the icon (This is the missing 'All' from Media room)
```
type: custom:button-card
tap_action:
  action: toggle
hold_action:
  action: more-info
entity: light.media_room
show_state: false
show_icon: true
name: All
size: 25px
styles:
  card:
    - font-size: 14px
    - font-weight: bold
state:
  - value: 'off'
    icon: hue:ceiling-round
  - value: 'on'
    icon: hue:ceiling-round
```
