### ISSUE TITLE
Icon Request Hue Scenes

### ISSUE THREAD

**Issue by m4tthall73** [arallsopp/hass-hue-icons#233]
Would it be possible to add the scene icons, such as those found here?

https://github.com/mattmon/hue-scene-icons

**Comment by arallsopp** [comment]
Howdo @m4tthall73. Those icons look to be full colour png files. Hass-hue-icons uses svg files which are scalable vectors. Whilst this makes them great for high resolution display and encapsulation within a .js file, they'd be very hard to include full colour bitmaps like these. I'll put a word out to @mattmon and see if they have a way forwards that might make sense for collaboration.

**Comment by mattmon** [comment]
@arallsopp deserves all the credit for actually creating something... These vector icons are fantastic!

I just wrote a hacky script that captures the existing icons, haha

The two icon sets, while both hue related, actually apply to separate parts of HA and in different ways.

The vector icons set can be easily integrated with home assistant and used throughout the native interface; while the pngs need to be programmatically applied through yaml customization.

I'm all for collaboration. Given all the drama about hue accounts lately, maybe the right way to approach it is in creating a set of resources for people to use to replace the hue hub in their own HA setups.

Between the icons discussed here, projects like DIYhue and snippets from the HA forums - there is a very usable alternative, it's just not particularly easy to find and configure all the distinct parts.

It might make sense to bundle @Mariusthvdb's [scene selector](https://community.home-assistant.io/t/select-activate-hue-scenes-in-new-v2-api-setup/356057) with the png icons into a more easily installable package.  

From there, maybe we could work together to assemble some documentation on how to use all the projects together to make your own uberHue?

**Comment by Mariusthvdb** [comment]
well, ive used my images for a few years now, and yes, they're the same as linked in that repo. Also, I used core HA customize to add them to the scenes in HA directly:

```
homeassistant:

  customize_glob:

    scene.*arctische_dageraad:
      entity_picture: /local/hue_scenes/arctische_dageraad.png

    scene.*chinatown:
      entity_picture: /local/hue_scenes/chinatown.png

    scene.*concentreren:
      entity_picture: /local/hue_scenes/concentreren.png

    scene.*_disturbia:
      entity_picture: /local/hue_scenes/disturbia.png

    scene.*energie:
      entity_picture: /local/hue_scenes/energie.png

    scene.*feestelijk_plezier:
      entity_picture: /local/hue_scenes/feestelijk_plezier.png

    scene.*gedimd:
      entity_picture: /local/hue_scenes/gedimd.png

    scene.*gouden_ster:
      entity_picture: /local/hue_scenes/gouden_ster.png

    scene.*gouden_vijver:
      entity_picture: /local/hue_scenes/gouden_vijver.png

    scene.*helder:
      entity_picture: /local/hue_scenes/helder.png

    scene.*herfstgoud:
      entity_picture: /local/hue_scenes/herfstgoud.png

    scene.*honolulu:
      entity_picture: /local/hue_scenes/honolulu.png

etcetcetc
```

ofc, the Hue Icons by Andy complete this for the lights and other devices we set custom icons for, really love those, and use them a lot. 

result is a nice Frontend representation, without anything else todo but drop in my package and install Andy's icons ;-)

____
other than that, not really sure what to add, it's been like this since I opened that topic when was it, 2 years ago?

personally I dont think it has anything to do with creating our own Hue, because we need the Hue integration for this, and I am still fully supportive of that work by Marcel, who did an amazing job with the Hue integration and APi2.

so, imo, we dont need new resources, its all out there, and packaged as it is.

let me know what else you had mind and if I can help.
